### ISSUE TITLE
404 on https://beefore.readthedocs.io/

### ISSUE THREAD

**Issue by AnneTheAgile** [pybee/beefore#2]
The readme says docs are at https://beefore.readthedocs.io/
but today I got a creative asciiart instead: 

Read the Docs

```
Log in


    \          SORRY            /
     \                         /
      \    This page does     /
       ]   not exist yet.    [    ,'|
       ]                     [   /  |
       ]___               ___[ ,'   |
       ]  ]\             /[  [ |:   |
       ]  ] \           / [  [ |:   |
       ]  ]  ]         [  [  [ |:   |
       ]  ]  ]__     __[  [  [ |:   |
       ]  ]  ] ]\ _ /[ [  [  [ |:   |
       ]  ]  ] ] (#) [ [  [  [ :===='
       ]  ]  ]_].nHn.[_[  [  [
       ]  ]  ]  HHHHH. [  [  [
       ]  ] /   `HH("N  \ [  [
       ]__]/     HHH  "  \[__[
       ]         NNN         [
       ]         N/"         [
       ]         N H         [
      /          N            \
     /           q,            \
    /                           \
```

Copyright 2010 - 2016. Created by Eric Holscher, Charles Leifer, and Bobby Grace for the 2010 Django Dash.
GitHub | Docs. Made by humans. Funded by readers like you.

//Update; 
Readthedocs refers to several required steps; 
1.Account on Readthedocs to link to the code here on github.
https://read-the-docs.readthedocs.io/en/latest/getting_started.html#import-docs
2.Folder /docs to contain the Sphinx website, constructed via make after pip install sphinx. 
The first  tutorial is here https://youtu.be/oJsUvBQyHBs?t=446

Part [1] the admin here would need to do. 
Part [2] I could at least make a hello world type of doc, if that is agreeable.

**Comment by freakboy3742** [comment]
Thanks for the report. I need to flesh out the docs for beefore - but first I need to get the code to a point where it's stable enough to push a release to PyPI. It's not *that* far off, though.

**Comment by rhyspowell** [comment]
First run at documentation created in pr #18 

This was mainly done to give me an understanding of what happens. I hope that it also points people into the right direction.

Anything that's further needed, please let me know

**Comment by rhyspowell** [comment]
@freakboy3742 with the PR being merged in, this can be close now.
